### PR TITLE
rewrite xmm2usb in plain shellscript

### PR DESCRIPTION
**Pull request by Gottox**
this removes the system dependency to python and allows to run this
script in early userspace.

### CODE REVIEW

**Comment by abrasive** [comment]
Thanks for your generous support! And thanks for this PR; I'll review this when I get a minute.

I take it this was successful on your machine; could you tell me the machine model name and part number? I'll start a list of working/non working devices, there will definitely be ACPI hassles for some.

**Comment by Gottox** [comment]
Yes, it's a bit clumsy for now, but I was able to get an LTE connection.

```
$ sudo dmidecode | grep -A3 '^System Information' 
System Information
	Manufacturer: LENOVO
	Product Name: 20QFCTO1WW
	Version: ThinkPad X1 Yoga 4th
```

**Comment by NikosAlexandris** [comment]
> Yes, it's a bit clumsy for now, but I was able to get an LTE connection.

Just to confirm: you got the module working, like really having access to the internet?  :-)

**Comment by Gottox** [comment]
Yes:
image

**Comment by kopax** [comment]
May I get some support #1 I'd like to get internet too.

**Comment by abrasive** [comment]
Merged. Thanks again!

**Pull request closed without merging**
